### PR TITLE
Add sensitive data encryption

### PR DESCRIPTION
**Pull request by McKay1717**

### CODE REVIEW

**Comment by McKay1717** [comment]
Some bug exist in this commit, this feature isn't totally done

**Comment by coffnix** [comment]
Merge is very dangerous?

**Comment by McKay1717** [comment]
Some data could not be decrypted .
Currently i search a similarity between the decrypted string.
Sorry for the bad pull request i'm going to fix that

**Comment by McKay1717** [comment]
Okay the main problem was identified.

**Comment by McKay1717** [comment]
All done, i'm going to commit the fix

**Pull request closed without merging**
