### PR TITLE
IPV6 Ready !

### PR DESCRIPTION
**Pull request by McKay1717**
Edit sql shema:
- Field ip is now a varbinary(32) , that allow ipv6

Use INET6_ATON instead of INET_ATON.
IP is now encoded in Hexa in BDD
/!\ Warning MySQL 5.6 or more is requiered /!\

### CODE REVIEW

**Comment by coffnix** [comment]
This update require mysql 5.6 to use mysar-ng? or only to import logs on ipv6?
This update break mysar-ng on mysql < 5.6 ?

**Comment by McKay1717** [comment]
I have rewritten all INET_ATON with INET6_ATON .
INET6_ATON was implemented in MySql 5.6.
So Mysql 5.6 is required for import all logs and for display.
This upgrade break mysar-ng with older MySQL server.

**Comment by coffnix** [comment]
It would then be interesting to do a project versioning 1.0 would be the current mysar-ng and 2.0 would be the new version with support for MySQL 5.6 or higher. It can be done this way?

**Comment by McKay1717** [comment]
If you want to process with this way, You can merge your current master branch in a new branch named v1 and marge my pull request in Master.

**Comment by coffnix** [comment]
Done, please test. :D

**Comment by McKay1717** [comment]
All seem to be correct ;)

**Pull request merged**
